config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  namespace :admin do
    resources :users do
      resources :user_details
    end 

     resources :users do
      resources :user_books
    end 
  end
  
  #  resources :users do
  #     resources :user_details
  # end  
  
  #  resources :users do
  #     resources :user_books
  # end

  resources :categories do 
   resources :books
  end
  
  root to: "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
        
   has_many :user_details, dependent: :destroy
   has_many :user_books, dependent: :destroy
   
  validates :name, presence: true, uniqueness: true
 
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
 before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)       
      if @user.save
         redirect_to admin_users_path, notice: 'User was successfully created.'
      else
      	flash.now[:alert] = 'User not created' 
        render :new
      end
  end

  def update
      if @user.update(user_params)
       redirect_to admin_users_path, notice: 'User was successfully updated.'
      else
      	flash.now[:alert] = 'User not updated' 
        render :edit 
      end
  end

  def show
  end

  def destroy
    @user.destroy
     redirect_to admin_users_path, notice: 'User was successfully destroyed.'
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :active)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)       
      if @user.save
         redirect_to users_path, notice: 'User was successfully created.'
      else
      	flash.now[:alert] = 'User not created' 
        render :new
      end
  end

  def update
      if @user.update(user_params)
       redirect_to users_path, notice: 'User was successfully updated.'
      else
      	flash.now[:alert] = 'User not updated' 
        render :edit 
      end
  end

  def show
  end

  def destroy
    @user.destroy
     redirect_to users_path, notice: 'User was successfully destroyed.'
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :password, :active)
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

<hr class="border">
<div class="mmt-credentials-form mmt-account-settings-form">
  <div class="col-lg-12 col-md-12">
    <div class="form-group">
      <%= f.label :name %>
        <%= f.text_field :name %>
    </div>
  </div>

  <div class="col-lg-12 col-md-12">
    <div class="form-group">
      <%= f.label :email %>
        <%= f.text_field :email %>
    </div>
  </div>

  <div class="col-lg-12 col-md-12">
   <div class="form-group">
    <%= f.label :password %>
    <%= f.text_field :password %>
   </div>
  </div>

  <div class="col-lg-12 col-md-12">
   <div class="form-group">
    <%= f.label :active %>
    <span class="form-feild">
      <%= f.select :active, options_for_select([['Yes', "true"], ['No', "false"]], @user.active), {}, class: 'selectpicker select-controller' %>
    </span>
   </div>
  </div>
  
  <div class="col-lg-12 col-md-12">
   <div class="col-md-8">
    <%= f.submit %>
  </div>
  </div>
</div>
<%end%>

app/views/users/_user.html.erb
<tr>
  <td><%= user.name %></td>
  <td><%= user.email %></td>
  <td><%= user.active %></td>
  <td class="actions">
    <%= link_to 'Edit', edit_user_path(user) %>
    <%= link_to 'Delete', user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %> 
    <%#= link_to 'UserDetails', user_user_details_path(user, @user_detail)%> 
    <%#= link_to 'UserBooks', user_user_books_path(user, @user_book)%> 
  </td>
</tr>

app/views/users/edit.html.erb
<div class="container">
<h2>Edit User</h2>
<hr class="border">
<%#= form_for @user, url: user_path(@user), method: :put do |f| %>

<%= render 'form', f:f %>
<%# end %>
</div>

app/views/users/index.html.erb
<div class="container main-container">
  <div class="main-container-top">
    <div class="filter-icons">
      <ul class="nav navbar-nav navbar-right">
        <%= link_to 'New', new_user_path %>
      </ul>
    </div>
    <p id="notice"><%= notice %></p>
     <h1>Users</h1>
     <hr class="border">
     <div class="table-structure">
       <table class="table table-bordered">
         <thead>
           <tr>
              <th>Name</th>
              <th>Email</th>
              <th>Active</th>
              <th class="actions">Actions</th>
           </tr>
         </thead>
         <body>
            <%= render @users %>
         </body>
       </table>
     </div>
 </div>
</div>

app/views/users/new.html.erb
<div class="container">
 <h2>New User</h2>
 <hr class="border">
 <%#= form_for @user, url: users_path, method: :get do |f| %>
 
 <%= render 'form', f:f %>
 <%# end %>
</div>

app/views/users/show.html.erb
<div class="container main-container">
  <div class="main-container-top">
    <div class="filter-icons">
      <ul class="nav navbar-nav navbar-right">
        <%= link_to 'Edit', edit_user_path(@user) %> 
      </ul>
    </div>
  </div>
  <p id="notice"><%= notice %></p>
  <h3>Uesr - Details</h3> 
    <hr class="border">
     
    <p>
      <strong>Name:</strong>
      <%= @user.name %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @user.email %>
    </p>

    <p>
      <strong>Password:</strong>
      <% @user.password %>
    </p>

    <p>
      <strong>Active:</strong>
      <%= @user.active %>
    </p>

</div> 