config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  namespace :admin do
    resources :users do
      resources :user_details
    end 

     resources :users do
      resources :user_books
    end 
  end
  
  #  resources :users do
  #     resources :user_details
  # end  
  
  #  resources :users do
  #     resources :user_books
  # end

  resources :categories do 
   resources :books
  end
  
  root to: "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user_book.rb
class UserBook < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/admin/user_books_controller.rb
class Admin::UserBooksController < ApplicationController
  before_action :set_user
  before_action :set_user_book, only: [:show, :edit, :update, :destroy]

  def index
    @user_books = UserBook.all
  end
  
  def new
    @user_book = UserBook.new
  end

  def edit

  end

  def create
    @user_book = @user.user_books.new(user_params)       
      if @user_book.save
         redirect_to admin_user_user_books_path, notice: 'UserBook was successfully created.'
      else
      	flash.now[:alert] = 'UserBook not created' 
        render :new
      end
  end

  def update
      if @user.user_books.update(user_params)
         redirect_to admin_user_user_books_path, notice: 'UserBook was successfully updated.'
      else
      	flash.now[:alert] = 'UserBook not updated' 
        render :edit 
      end
  end

  def show
  end

  def destroy
    @user_book.destroy
     redirect_to admin_user_user_books_path, notice: 'UserBook was successfully destroyed.'
  end

  private
    def set_user
      @user = User.find(params[:user_id])
    end 
    
    def set_user_book
      @user_book = UserBook.find(params[:id])
    end

    def user_params
      params.require(:user_book).permit(:user_id, :book_id, :return_date, :shipping_address)
    end
end

app/controllers/user_books_controller.rb
class UserBooksController < ApplicationController
  before_action :set_user
  before_action :set_user_book, only: [:show, :edit, :update, :destroy]

  def index
    @user_books = UserBook.all
  end
  
  def new
    @user_book = UserBook.new
  end

  def edit

  end

  def create
    @user_book = @user.user_books.new(user_params)       
      if @user_book.save
         redirect_to user_books_path, notice: 'UserBook was successfully created.'
      else
      	flash.now[:alert] = 'UserBook not created' 
        render :new
      end
  end

  def update
      if @user.user_books.update(user_params)
         redirect_to user_books_path, notice: 'UserBook was successfully updated.'
      else
      	flash.now[:alert] = 'UserBook not updated' 
        render :edit 
      end
  end

  def show
  end

  def destroy
    @user_book.destroy
     redirect_to user_books_path, notice: 'UserBook was successfully destroyed.'
  end

  private
    def set_user
      @user = User.find(params[:user_id])
    end 
    
    def set_user_book
      @user_book = UserBook.find(params[:id])
    end

    def user_params
      params.require(:user_book).permit(:user_id, :book_id, :return_date, :shipping_address)
    end
end

app/helpers/user_books_helper.rb
module UserBooksHelper
end

app/views/user_books/_form.html.erb
<%#= form_for(@user) do |f| %>

  <div class="field">
    <%= f.label :return_date %>
    <%= f.date_select(:return_date,:start_year => 1990) %>
  </div>
  
  <div class="field">
    <%= f.label :shipping_address%>
    <%= f.text_field :shipping_address %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<%# end %>

app/views/user_books/_user_detail.html.erb
<tr>
  <td><%= user_book.return_date %></td>
  <td><%= user_book.shipping_address %></td>
  <td class="actions">
    <%= link_to 'Edit', edit_user_user_book_path(@user, user_book) %>
    <%= link_to 'Delete', user_user_book_path(@user, user_book), method: :delete, data: { confirm: 'Are you sure?' } %>    
  </td>
</tr>

app/views/user_books/edit.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
<h2>Edit UserBook</h2>
<hr class="border">
<%= form_for @user_books, url: edit_user_user_book_path, method: :patch  do |f| %>

<%= render 'form', f:f %>
<% end %>
</div>

app/views/user_books/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
<h1>UserBooks</h1>
<hr class="border">
<table class="table table-bordered">
  <thead>
    <tr>
      <th>ReturnDate</th>
      <th>ShippingAddress</th>
      <th class="actions">Actions</th>
    </tr>
  </thead>

  <tbody>   
   <%= render @user_books %>  
  </tbody>
</table>
</div>

app/views/user_books/new.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
<h2>New UserBooks</h2>
<hr class="border">
<%=@user_book.errors.full_messages.to_sentence %>

<%= form_for @user_book, url: user_user_books_path, method: :post  do |f| %>

<%= render 'form', f:f %>
<% end %>
</div>

app/views/user_books/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
  <h3>UserBook - Show</h3>
 <%= link_to 'Edit', edit_user_book_path(@user_book) %> 
 
<p>
  <strong>ReturnDate:</strong>
  <%= @user_detail.return_date %>
</p>

<p>
  <strong>ShippingAddress:</strong>
  <%= @user_detail.shipping_address %>
</p>
</div>  