config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  namespace :admin do
    resources :users do
      resources :user_details
    end 

     resources :users do
      resources :user_books
    end 
  end
  
  #  resources :users do
  #     resources :user_details
  # end  
  
  #  resources :users do
  #     resources :user_books
  # end

  resources :categories do 
   resources :books
  end
  
  root to: "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user_detail.rb
class UserDetail < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/admin/user_details_controller.rb
class Admin::UserDetailsController < ApplicationController
  before_action :set_user
  #before_action :set_book
  before_action :set_user_detail, only: [:show, :edit, :update, :destroy]

  def index
    @user_details = UserDetail.all
  end
  
  def new
    @user_detail = UserDetail.new
  end

  def edit

  end

  def create
    @user_detail = @user.user_details.new(user_params)       
      if @user_detail.save
         redirect_to admin_user_user_details_path, notice: 'User was successfully created.'
      else
      	flash.now[:alert] = 'User not created' 
        render :new
      end
  end

  def update
      if @user.user_details.update(user_params)
         redirect_to admin_user_user_details_path, notice: 'User was successfully updated.'
      else
      	flash.now[:alert] = 'User not updated' 
        render :edit 
      end
  end

  def show
  end

  def destroy
    @user_detail.destroy
     redirect_to admin_user_admin_user_details_path, notice: 'User was successfully destroyed.'
  end

  private
    def set_user
      @user = User.find(params[:user_id])
    end 
    
    # def set_book
    #   @book = Book.find(params[:book_id])
    # end 

    def set_user_detail
      @user_detail = UserDetail.find(params[:id])
    end

    def user_params
      params.require(:user_detail).permit(:category, :book_id, :return_date)
    end
end

app/controllers/user_details_controller.rb
class UserDetailsController < ApplicationController
  before_action :set_user
  before_action :set_user_detail, only: [:show, :edit, :update, :destroy]

  def index
    @user_details = UserDetail.all
  end
  
  def new
    @user_detail = UserDetail.new
  end

  def edit

  end

  def create
    @user_detail = @user.user_details.new(user_params)       
      if @user_detail.save
         redirect_to user_details_path, notice: 'UserDetail was successfully created.'
      else
      	flash.now[:alert] = 'UserDetail not created' 
        render :new
      end
  end

  def update
      if @user.user_details.update(user_params)
         redirect_to user_details_path, notice: 'UserDetail was successfully updated.'
      else
      	flash.now[:alert] = 'UserDetail not updated' 
        render :edit 
      end
  end

  def show
  end

  def destroy
    @user_detail.destroy
     redirect_to user_details_path, notice: 'UserDetail was successfully destroyed.'
  end

  private
    def set_user
      @user = User.find(params[:user_id])
    end 
    
    def set_user_detail
      @user_detail = UserDetail.find(params[:id])
    end

    def user_params
      params.require(:user_detail).permit(:user_id, :book_id, :return_date)
    end
end

app/helpers/admin/user_details_helper.rb
module Admin::UserDetailsHelper
end

app/helpers/user_details_helper.rb
module UserDetailsHelper
end

app/views/user_details/_form.html.erb
<%#= form_for(@user) do |f| %>

  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

   <div class="field">
    <%= f.label :book%>
    <%= f.text_field :book %>
  </div>

  <div class="field">
    <%= f.label :return_date %>
    <%= f.date_select(:return_date,:start_year => 1990) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<%# end %>

app/views/user_details/_user_detail.html.erb
<tr>
  <td><%= user_detail.return_date %></td>
  <td class="actions">
    <%= link_to 'Edit', edit_user_user_detail_path(@user, user_detail) %>
    <%= link_to 'Delete', user_user_detail_path(@user, user_detail), method: :delete, data: { confirm: 'Are you sure?' } %>    
  </td>
</tr>

app/views/user_details/edit.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
<h2>Edit UserDetails</h2>
<%= form_for @user_details, url: user_details_path, method: :patch  do |f| %>

<%= render 'form', f:f %>
<% end %>
</div>

app/views/user_details/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
<h1>UserDetails</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>CategoryId</th>
      <th>BookId</th>
      <th>ReturnDate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_details.each do |user| %>
      <tr>
        <td><%= user.category %></td>
        <td><%= user.book %></td> 
        <td><%= user.return_date %></td>
        <td><%= link_to 'New', new_user_detail_path(user) %></td>
        <td><%= link_to 'Edit', edit_user_detail_path(user) %></td>
        <td><%= link_to 'Destroy', user_detail_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/user_details/new.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
<h2>New UserDetails</h2>
<hr class="border">
<%=@user_detail.errors.full_messages.to_sentence %>
<%= form_for @user_detail, url: user_details_path, method: :post  do |f| %>

<%= render 'form', f:f %>
<% end %>
</div>

app/views/user_details/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
  <h3>UserDeatils - Show</h3>
  <hr class="border">
 <%= link_to 'Edit', edit_user_detail_path(@user_detail) %> 

<p>
  <strong>ReturnDate:</strong>
  <%= @user_detail.return_date %>
</p>

</div>  